### ISSUE TITLE
Database [schema] migrations?

### ISSUE THREAD

**Issue by moll** [citizenos/citizenos-api#1]
Hey!

Thought I'd open up your GitHub issues page with a question. Once the app's database is initialized (which I believe happened on the first run), how do you handle further database changes? Thanks!

**Comment by tiblu** [comment]
@moll Thanks! Finally migrations have landed - https://github.com/citizenos/citizenos-api/wiki/DB-Migrations

I'm not sure if the information is sufficient or not.

Also, I used NPM scripts instead of suggested `make` just to use tools that Node community is used to.

I guess I should describe the Citizen OS versioning and upgrade/downgrade processes in a separate Wiki post - https://github.com/citizenos/citizenos-api/issues/21

Any ideas and comments are more than welcome!
