### ISSUE TITLE
E-mails: Review copy texts of existing e-mails

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#132]
**Overview**

We send out several e-mails which MAY need to be reviewed so that the information is on point and we use good tone of voice.

**TODO (feel free to modify):**

- [x] Review the texts, improve where possible
- [ ] Make sure the texts and visual layout matches the new Topic Report e-mails  - for more info see https://github.com/citizenos/citizenos-api/issues/5

**List of e-mails that are being sent out**

![image (2)](https://user-images.githubusercontent.com/7405383/56130771-7f76d600-5f8e-11e9-9f37-9d923d80b8f8.png)
![image (3)](https://user-images.githubusercontent.com/7405383/56130772-800f6c80-5f8e-11e9-8c54-d5429b51b6ff.png)
![image](https://user-images.githubusercontent.com/7405383/56130773-800f6c80-5f8e-11e9-999c-9fa1e10cdff3.png)
![image (1)](https://user-images.githubusercontent.com/7405383/56130775-800f6c80-5f8e-11e9-9462-d45ac249960c.png)

**Comment by anettlinno** [comment]
@oksks we would need your copy-magic here :))

**Comment by anettlinno** [comment]
I could not replicate the copy which is probably fixed but the text alignment in center looks weird and I would align the text on the left side. This should also solve the current bulleting issue (tbh I would rather use numbering there instead of bulleting):

<img width="619" alt="Report" src="https://user-images.githubusercontent.com/45175679/204535662-a26a9780-f700-40b8-b45f-acb86ca72104.png">

**Comment by ilmartyrk** [comment]
@anettlinno changed the layout and bullet list to numbered list

**Comment by anettlinno** [comment]
@ilmartyrk I received it still the same (in test environment though)

<img width="610" alt="Testtest" src="https://user-images.githubusercontent.com/45175679/204738276-58efe9ee-fbff-4731-9358-880e17642619.png">

**Comment by ilmartyrk** [comment]
Should be fixed, at least working in my local setup
